# Generated by Django 4.0.4 on 2022-06-04 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rental_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
