# Generated by Django 4.2.1 on 2023-06-19 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(upload_to='parts/')),
                ('country', models.CharField(max_length=60)),
                ('country_ar', models.CharField(blank=True, max_length=60, null=True)),
                ('in_stock', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
