# Generated by Django 4.2.1 on 2023-06-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='brand',
        ),
        migrations.AddField(
            model_name='part',
            name='country_ar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
