# Generated by Django 4.1.7 on 2023-03-27 01:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('picture', models.ImageField(upload_to='cars/')),
                ('plate_numbers', models.CharField(max_length=10, unique=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('rental_price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
