# Generated by Django 4.2.1 on 2023-06-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
