# Generated by Django 4.2.1 on 2023-06-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcar',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='rental_car'),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='rental_car'),
        ),
    ]
