# Generated by Django 4.2.1 on 2023-06-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_milage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='milage_ar',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
