# Generated by Django 4.2.1 on 2023-06-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rentalcar_car_sellcar_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='sell_car'),
        ),
    ]
