# Generated by Django 4.2.1 on 2023-06-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_owner_car_owner_ar_car_seller_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='engine_capacity',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='engine_capacity_ar',
            new_name='engine_ar',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuel_type',
            new_name='fuel',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuel_type_ar',
            new_name='fuel_ar',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='kms_driven',
            new_name='km_driven',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='milage_ar',
            new_name='mileage_ar',
        ),
    ]
